### ISSUE TITLE
Clear downloads not working with large intervals

### ISSUE THREAD

**Issue by Mornon** [stefanXO/Always-Clear-Downloads#1]
Automatic download cleaning works well with small intervals, like 5 seconds, but I tried with 3600 s (since I don't have any need for the list to be cleaned every few seconds, once every hour or so would be more than enough) and it doesn't work.

Steps to reproduce:

- set the frequency to 3600 s
- download a file

Expected behaviour: after one hour the list should be cleared.

Actual behaviour: the list isn't cleared even after days.

**Comment by mastef** [comment]
That's right, it would work with exactly 3599s. 

Currently the app is [reloading the config hourly](https://github.com/stefanXO/Always-Clear-Downloads/blob/master/background.js#L101), to make sure it's not stuck based on an error. Can you try with something like 3500 instead?

I'm not sure I'd want to fix this, maybe a note in the options page would be enough.

**Comment by mastef** [comment]
@Mornon should be fixed in 2.0.0 which has just been published in the Chrome Webstore
